"""initial

Revision ID: f78bb9f171af
Revises: 
Create Date: 2026-03-09 19:48:10.370115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'f78bb9f171af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('admin_id', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order_num', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('partner_preference', sa.String(length=20), nullable=True),
    sa.Column('goal', sa.String(length=30), nullable=True),
    sa.Column('raw_intro_text', sa.Text(), nullable=True),
    sa.Column('intro_summary', sa.Text(), nullable=True),
    sa.Column('personality_type', sa.String(length=100), nullable=True),
    sa.Column('profile_text', sa.Text(), nullable=True),
    sa.Column('attachment_hint', sa.String(length=20), nullable=True),
    sa.Column('primary_dimension', sa.String(length=20), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ideal_partner_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('onboarding_step', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), nullable=False),
    sa.Column('flag_for_review', sa.Boolean(), nullable=False),
    sa.Column('prompt_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index('idx_users_active', 'users', ['is_active', 'is_paused', 'is_banned'], unique=False)
    op.create_index('idx_users_goal_city', 'users', ['goal', 'city'], unique=False, postgresql_where=sa.text('is_active IS true'))
    op.create_index('idx_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_table('aggregated_impressions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('impression_text', sa.Text(), nullable=False),
    sa.Column('based_on_count', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_key', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id')
    )
    op.create_index('idx_answers_user_id', 'answers', ['user_id'], unique=False)
    op.create_table('block_list',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blocked_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'blocked_user_id')
    )
    op.create_table('consent_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('ip_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_match_quota',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('count', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    op.create_table('interview_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collected_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('turn_count', sa.SmallInteger(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('date_prep_text', sa.Text(), nullable=True),
    sa.Column('user1_action', sa.String(length=10), nullable=True),
    sa.Column('user2_action', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('chat_opened_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('chat_deadline', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('chat_status', sa.String(length=20), nullable=False),
    sa.Column('prompt_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('matched_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('user1_id < user2_id'),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id')
    )
    op.create_index('idx_matches_status', 'matches', ['status'], unique=False)
    op.create_index('idx_matches_user1', 'matches', ['user1_id'], unique=False)
    op.create_index('idx_matches_user2', 'matches', ['user2_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('moderation_status', sa.String(length=20), nullable=False),
    sa.Column('nudenet_score', sa.Float(), nullable=True),
    sa.Column('nudenet_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('moderated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('moderated_by', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('idx_photos_status', 'photos', ['moderation_status'], unique=False)
    op.create_index('idx_photos_user_id', 'photos', ['user_id'], unique=False)
    op.create_table('user_embeddings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chat_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('for_user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['for_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'for_user_id')
    )
    op.create_table('contact_exchange',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'user_id')
    )
    op.create_table('date_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('did_meet', sa.Boolean(), nullable=True),
    sa.Column('comfort_level', sa.SmallInteger(), nullable=True),
    sa.Column('wants_second_date', sa.String(length=10), nullable=True),
    sa.Column('one_word_impression', sa.String(length=30), nullable=True),
    sa.Column('ai_reflection', sa.Text(), nullable=True),
    sa.Column('prompt_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'user_id')
    )
    op.create_table('match_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('audio_key', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('is_filtered', sa.Boolean(), nullable=False),
    sa.Column('filter_category', sa.String(length=50), nullable=True),
    sa.Column('filter_level', sa.SmallInteger(), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_messages_match_id', 'match_messages', ['match_id', 'created_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['reported_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('auto_detected', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['match_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_reports')
    op.drop_table('reports')
    op.drop_index('idx_match_messages_match_id', table_name='match_messages')
    op.drop_table('match_messages')
    op.drop_table('date_feedback')
    op.drop_table('contact_exchange')
    op.drop_table('chat_analysis')
    op.drop_table('user_embeddings')
    op.drop_index('idx_photos_user_id', table_name='photos')
    op.drop_index('idx_photos_status', table_name='photos')
    op.drop_table('photos')
    op.drop_index('idx_matches_user2', table_name='matches')
    op.drop_index('idx_matches_user1', table_name='matches')
    op.drop_index('idx_matches_status', table_name='matches')
    op.drop_table('matches')
    op.drop_table('interview_sessions')
    op.drop_table('daily_match_quota')
    op.drop_table('consent_log')
    op.drop_table('block_list')
    op.drop_index('idx_answers_user_id', table_name='answers')
    op.drop_table('answers')
    op.drop_table('aggregated_impressions')
    op.drop_index('idx_users_telegram_id', table_name='users')
    op.drop_index('idx_users_goal_city', table_name='users', postgresql_where=sa.text('is_active IS true'))
    op.drop_index('idx_users_active', table_name='users')
    op.drop_table('users')
    op.drop_table('questions')
    op.drop_table('prompt_versions')
    op.drop_table('moderation_log')
    # ### end Alembic commands ###
